version: "3.7"
services:
  school-service-eureka:
    hostname: discovery
    image: localhost:5000/cloud-eureka:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    networks:
      - school-service-swarm-net
    restart: unless-stopped

  school-service-student:
    image: localhost:5000/school-service-student:0.0.1-SNAPSHOT
    ports:
      - 8080:8080
    networks:
      - school-service-net
    depends_on:
      - school-service-swarm-eureka
    restart: unless-stopped
    links:
      - school-service-eureka:discovery

  school-service-ribbon:
    image: localhost:5000/school-service-ribbon:0.0.1-SNAPSHOT
    ports:
      - 8082:8082
    networks:
      - school-service-swarm-net
    depends_on:
      - school-service-eureka
    restart: unless-stopped
    links:
      - school-service-eureka:discovery

networks:
  school-service-swarm-net:
